### ISSUE TITLE
Request to Add Document Feature

### ISSUE THREAD

**Issue by kumard29** [senthild29/SeleniumRepo#4]
Hi Senthild29

Can you please include a new feature to add documents(pdf,txt,xls..) to existing attachment feature.

**Comment by senthild29** [comment]
Hi Kumard29,

Thanks for suggesting to add new document attachment feature to our product WhatsUp, will do the required changes and revert back shortly.

**Comment by senthild29** [comment]
Dear Kumard29,

As suggested, we have added documents(pdf,txt,xls,csv,doc) feature to attachment. Thanks for your valuable feedback
